format = "$all"

[directory]
truncation_symbol = "…/"
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[kubernetes]
disabled = false

[status]
disabled = false

[sudo]
disabled = false

[time]
disabled = false

[gcloud]
symbol = '️🇬️  '
format = 'on [$symbol$project(\($region\))]($style) '

[gcloud.region_aliases]
europe-west1 = 'ew1'
europe-west4 = 'ew4'
asia-southeast1 = 'as1'

[gcloud.project_aliases]
a11s-dev = 'dev'
a11s-live = 'live'

