
# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule v1
# windowrule = float, ^(kitty)$

# Example windowrule v2
# windowrulev2 = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

windowrule = workspace 5 silent, class:spotify
windowrule = workspace 5 silent, class:org.telegram.desktop
windowrule = workspace 4 silent, class:Slack

workspace = 1, default:true, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, defaultName:q, persistent:true, monitor:DP-1
workspace = 7, defaultName:w, persistent:true, monitor:DP-1
workspace = 8, defaultName:e, persistent:true, monitor:DP-1
workspace = 9, defaultName:r, persistent:true, monitor:DP-1
